name: Generate contribution snake

on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *"

permissions:
  contents: write

jobs:
  snake:
    runs-on: ubuntu-latest
    steps:
      - name: Generate snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: mhinata2010-wq
          outputs: |
            dist/snake.svg?color_snake=%238250df&color_dots=%23ebedf0,%23d8c7f7,%23b794f4,%238250df,%235a32a3

      - name: Publish SVG
        uses: crazy-max/ghaction-github-pages@v3.1.0
        with:
          target_branch: output
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
